spring.application.name=actividades-api

server.port=8181

# Almacenamiento local de imágenes
storage.local.base-path=uploads/actividades
storage.local.base-url=http://localhost:8181/uploads/actividades

# Para servir los archivos estáticos desde Spring
spring.web.resources.static-locations=file:uploads/

#MySQL
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/gestion_actividades
spring.datasource.username=root
spring.datasource.password=3710belA;
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
